stages:
    - lint
    - test

cache:
  paths:
    - node_module

.rules:merge-request:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $WK_CI_CUSTOM_PIPELINE == null
          variables:
              WK_CI_CHANNEL: mr
              WK_CI_ENVIRONMENT: testing

.pnpm: 
    image:
        name: docker-registry.zhenguanyu.com/yuanfd/yfd_nodejs_ct8:22.4.0
    before_script:
        - (http_proxy=${WK_CI_PROXY_DEFAULT} https_proxy=${WK_CI_PROXY_DEFAULT} npm i -g pnpm@9.9.0)
        - (http_proxy=${WK_CI_PROXY_DEFAULT} https_proxy=${WK_CI_PROXY_DEFAULT} pnpm install)

lint:
    stage: lint
    tags:
        - kubernetes-runner
    extends:
        - .rules:merge-request
        - .pnpm
    needs: []
    script:
        - pnpm lint

test:
    stage: test
    tags:
        - kubernetes-runner
    extends:
        - .rules:merge-request
        - .pnpm
    needs: []
    script:
        - pnpm build:lib
        - pnpm test
